In [2]:
import torch

In [3]:
pretrain_file="../pretrained/bert-base-uncased-pytorch_model.bin"
# archive_file="bert-base-uncased-pytorch_model.bin"
pretrain_state_dict = torch.load(pretrain_file, map_location="cpu")

In [9]:
# for k in state_dict.keys():
#     print(k)
#     print(state_dict[k].shape)

bert.embeddings.word_embeddings.weight
torch.Size([30522, 768])
bert.embeddings.position_embeddings.weight
torch.Size([512, 768])
bert.embeddings.token_type_embeddings.weight
torch.Size([2, 768])
bert.embeddings.LayerNorm.gamma
torch.Size([768])
bert.embeddings.LayerNorm.beta
torch.Size([768])
bert.encoder.layer.0.attention.self.query.weight
torch.Size([768, 768])
bert.encoder.layer.0.attention.self.query.bias
torch.Size([768])
bert.encoder.layer.0.attention.self.key.weight
torch.Size([768, 768])
bert.encoder.layer.0.attention.self.key.bias
torch.Size([768])
bert.encoder.layer.0.attention.self.value.weight
torch.Size([768, 768])
bert.encoder.layer.0.attention.self.value.bias
torch.Size([768])
bert.encoder.layer.0.attention.output.dense.weight
torch.Size([768, 768])
bert.encoder.layer.0.attention.output.dense.bias
torch.Size([768])
bert.encoder.layer.0.attention.output.LayerNorm.gamma
torch.Size([768])
bert.encoder.layer.0.attention.output.LayerNorm.beta
torch.Size([768])
bert.encoder.l

In [4]:
from scipy.stats import truncnorm
def truncated_normal(size, threshold=1):
    values = truncnorm.rvs(-threshold, threshold, size=size)
    x = torch.from_numpy(values)
    return x

In [11]:
def reinitialize_weights():
    REINITIALIZE_WEIGHTS_FILE = "reinitialize_weights_layer10_layer11.bin"
    pretrain_file="../pretrained/bert-base-uncased-pytorch_model.bin"
    pretrain_state_dict = torch.load(pretrain_file, map_location="cpu")
    
    state_dict = {}
    for k in pretrain_state_dict.keys():
        if '.10.' in k or '.11.' in k:
            print('REINITIALIZED: ', k)
            parameters = truncated_normal(pretrain_state_dict[k].shape)
            state_dict[k] = parameters
        else:
            print('PRETAIN: ', k)
            state_dict[k] = pretrain_state_dict[k]
        
    torch.save(state_dict, REINITIALIZE_WEIGHTS_FILE)
    print("saved reinitialized weights: ", REINITIALIZE_WEIGHTS_FILE)
    
    return REINITIALIZE_WEIGHTS_FILE
    

In [12]:
reinitialize_weight_file = reinitialize_weights()
state_dict = torch.load(reinitialize_weight_file, map_location="cpu")


PRETAIN:  bert.embeddings.word_embeddings.weight
PRETAIN:  bert.embeddings.position_embeddings.weight
PRETAIN:  bert.embeddings.token_type_embeddings.weight
PRETAIN:  bert.embeddings.LayerNorm.gamma
PRETAIN:  bert.embeddings.LayerNorm.beta
PRETAIN:  bert.encoder.layer.0.attention.self.query.weight
PRETAIN:  bert.encoder.layer.0.attention.self.query.bias
PRETAIN:  bert.encoder.layer.0.attention.self.key.weight
PRETAIN:  bert.encoder.layer.0.attention.self.key.bias
PRETAIN:  bert.encoder.layer.0.attention.self.value.weight
PRETAIN:  bert.encoder.layer.0.attention.self.value.bias
PRETAIN:  bert.encoder.layer.0.attention.output.dense.weight
PRETAIN:  bert.encoder.layer.0.attention.output.dense.bias
PRETAIN:  bert.encoder.layer.0.attention.output.LayerNorm.gamma
PRETAIN:  bert.encoder.layer.0.attention.output.LayerNorm.beta
PRETAIN:  bert.encoder.layer.0.intermediate.dense.weight
PRETAIN:  bert.encoder.layer.0.intermediate.dense.bias
PRETAIN:  bert.encoder.layer.0.output.dense.weight
PRETAI

REINITIALIZED:  bert.encoder.layer.10.intermediate.dense.bias
REINITIALIZED:  bert.encoder.layer.10.output.dense.weight
REINITIALIZED:  bert.encoder.layer.10.output.dense.bias
REINITIALIZED:  bert.encoder.layer.10.output.LayerNorm.gamma
REINITIALIZED:  bert.encoder.layer.10.output.LayerNorm.beta
REINITIALIZED:  bert.encoder.layer.11.attention.self.query.weight
REINITIALIZED:  bert.encoder.layer.11.attention.self.query.bias
REINITIALIZED:  bert.encoder.layer.11.attention.self.key.weight
REINITIALIZED:  bert.encoder.layer.11.attention.self.key.bias
REINITIALIZED:  bert.encoder.layer.11.attention.self.value.weight
REINITIALIZED:  bert.encoder.layer.11.attention.self.value.bias
REINITIALIZED:  bert.encoder.layer.11.attention.output.dense.weight
REINITIALIZED:  bert.encoder.layer.11.attention.output.dense.bias
REINITIALIZED:  bert.encoder.layer.11.attention.output.LayerNorm.gamma
REINITIALIZED:  bert.encoder.layer.11.attention.output.LayerNorm.beta
REINITIALIZED:  bert.encoder.layer.11.inte

In [74]:
# total = 0 
# for k in state_dict.keys():
#     if 'weight' in k:
#         print(k)
#         total += 1 
    
#         print(state_dict[k].shape)

bert.embeddings.word_embeddings.weight
torch.Size([30522, 768])
bert.embeddings.position_embeddings.weight
torch.Size([512, 768])
bert.embeddings.token_type_embeddings.weight
torch.Size([2, 768])
bert.encoder.layer.0.attention.self.query.weight
torch.Size([768, 768])
bert.encoder.layer.0.attention.self.key.weight
torch.Size([768, 768])
bert.encoder.layer.0.attention.self.value.weight
torch.Size([768, 768])
bert.encoder.layer.0.attention.output.dense.weight
torch.Size([768, 768])
bert.encoder.layer.0.intermediate.dense.weight
torch.Size([3072, 768])
bert.encoder.layer.0.output.dense.weight
torch.Size([768, 3072])
bert.encoder.layer.1.attention.self.query.weight
torch.Size([768, 768])
bert.encoder.layer.1.attention.self.key.weight
torch.Size([768, 768])
bert.encoder.layer.1.attention.self.value.weight
torch.Size([768, 768])
bert.encoder.layer.1.attention.output.dense.weight
torch.Size([768, 768])
bert.encoder.layer.1.intermediate.dense.weight
torch.Size([3072, 768])
bert.encoder.layer.1.

In [11]:
len(self_generated_dict)

207

In [15]:
self_generated_dict['bert.encoder.layer.0.attention.self.query.weight'][10]

tensor([-0.0392,  0.7940,  0.5212, -0.8194, -0.0927, -0.1141, -0.1154, -0.8871,
         0.1155, -0.0987, -0.9839, -0.0524, -0.3792,  0.3771, -0.0448, -0.9734,
        -0.9338, -0.5460,  0.4948,  0.5826, -0.4724,  0.4210,  0.1925, -0.3941,
        -0.8376, -0.1763, -0.9071,  0.5935, -0.1801,  0.7270, -0.9954,  0.6480,
         0.3242, -0.7355,  0.0643, -0.2359,  0.7454, -0.2562, -0.3526, -0.5003,
         0.8909, -0.7294, -0.4778,  0.7649, -0.2613, -0.3540, -0.3341, -0.3892,
         0.4454,  0.1995, -0.6513, -0.0082, -0.8064, -0.1140, -0.3329, -0.4113,
         0.9518, -0.5713, -0.4802,  0.0392, -0.6485, -0.7797,  0.2227,  0.4778,
        -0.3169,  0.4430,  0.1516, -0.6602, -0.5672, -0.8043,  0.9785, -0.6142,
        -0.0452, -0.5278,  0.0739,  0.3931, -0.5565,  0.4845,  0.1360, -0.7983,
         0.2009, -0.1162, -0.0600, -0.1309,  0.6377,  0.4716,  0.3676,  0.3032,
        -0.2112, -0.8685,  0.0158, -0.0412, -0.2666, -0.6967,  0.5650,  0.6677,
         0.0451,  0.2603, -0.8925, -0.03

In [16]:
state_dict['bert.encoder.layer.0.attention.self.query.weight'][10]

tensor([-4.0774e-03, -5.5992e-02,  3.8239e-02, -3.3233e-02,  2.1458e-02,
        -6.4455e-02,  5.4764e-02,  4.3823e-02, -1.6064e-02,  1.8921e-02,
        -8.6033e-02,  4.8640e-02, -2.3422e-02, -6.5712e-02,  4.0450e-02,
         3.5652e-02, -3.4220e-02,  2.7226e-02,  2.5244e-02, -5.0143e-02,
         2.8682e-02, -1.5413e-02,  2.7495e-02, -3.6229e-02,  7.7442e-02,
        -4.8504e-02,  4.9910e-02, -3.6341e-02,  3.7231e-02, -7.6122e-02,
        -6.0755e-02, -8.4336e-02, -2.6144e-03, -1.7555e-02, -8.8574e-03,
         4.6355e-03,  6.5866e-03,  1.0598e-02, -1.4730e-02, -5.4885e-02,
        -2.4584e-02, -3.4590e-02,  2.8554e-02, -3.4476e-03,  2.1922e-02,
        -2.2579e-02, -1.4900e-02, -6.3395e-02, -2.5169e-02, -2.4746e-03,
         3.9507e-02,  2.3694e-02, -1.8066e-02, -1.2348e-01,  2.9972e-03,
         7.3432e-03,  7.0596e-03,  1.2542e-02,  9.1366e-03,  6.7050e-02,
        -1.6060e-03, -4.7604e-02, -5.5195e-02,  2.5834e-02,  2.1503e-02,
         1.3148e-02, -6.9125e-03, -1.9881e-02,  1.8

In [17]:
self_generated_dict['bert.encoder.layer.11.attention.self.query.weight'][10]

tensor([-5.0461e-02,  6.9734e-02, -3.1827e-02,  2.9276e-03, -1.6021e-02,
        -2.2153e-04,  2.4495e-02,  1.5918e-02, -1.5852e-02,  1.6580e-02,
        -6.6527e-03, -6.8142e-02, -1.0439e-02, -2.2604e-02,  3.4094e-03,
         5.0117e-02,  3.8181e-02,  1.5476e-02,  1.8190e-02, -1.7143e-02,
         4.2855e-02, -1.1223e-02,  1.8801e-02,  3.8932e-02, -1.2070e-03,
        -2.5220e-03,  1.1252e-02,  3.5875e-02, -1.1655e-02, -4.4611e-02,
        -3.5723e-02,  2.7098e-02, -2.5315e-02, -4.3921e-02, -3.3590e-02,
        -2.5316e-02, -2.5402e-03, -3.2093e-02,  1.7590e-02,  4.4715e-03,
        -4.2622e-02, -5.4426e-02,  5.5715e-03,  3.6474e-02,  2.0075e-02,
        -2.4211e-02,  1.1200e-01, -1.2124e-02,  6.2336e-03,  1.2563e-02,
        -6.5182e-02, -5.8309e-03, -4.3623e-03, -6.7238e-02,  1.9629e-03,
        -2.7483e-03,  6.2588e-03, -1.4956e-02, -3.1359e-02, -2.5026e-02,
         3.3577e-02, -2.6373e-03, -5.5331e-03,  5.0805e-03, -8.1706e-04,
         3.4413e-02, -3.2688e-02,  4.0914e-02, -6.5

In [18]:
state_dict['bert.encoder.layer.11.attention.self.query.weight'][10]

tensor([-5.0461e-02,  6.9734e-02, -3.1827e-02,  2.9276e-03, -1.6021e-02,
        -2.2153e-04,  2.4495e-02,  1.5918e-02, -1.5852e-02,  1.6580e-02,
        -6.6527e-03, -6.8142e-02, -1.0439e-02, -2.2604e-02,  3.4094e-03,
         5.0117e-02,  3.8181e-02,  1.5476e-02,  1.8190e-02, -1.7143e-02,
         4.2855e-02, -1.1223e-02,  1.8801e-02,  3.8932e-02, -1.2070e-03,
        -2.5220e-03,  1.1252e-02,  3.5875e-02, -1.1655e-02, -4.4611e-02,
        -3.5723e-02,  2.7098e-02, -2.5315e-02, -4.3921e-02, -3.3590e-02,
        -2.5316e-02, -2.5402e-03, -3.2093e-02,  1.7590e-02,  4.4715e-03,
        -4.2622e-02, -5.4426e-02,  5.5715e-03,  3.6474e-02,  2.0075e-02,
        -2.4211e-02,  1.1200e-01, -1.2124e-02,  6.2336e-03,  1.2563e-02,
        -6.5182e-02, -5.8309e-03, -4.3623e-03, -6.7238e-02,  1.9629e-03,
        -2.7483e-03,  6.2588e-03, -1.4956e-02, -3.1359e-02, -2.5026e-02,
         3.3577e-02, -2.6373e-03, -5.5331e-03,  5.0805e-03, -8.1706e-04,
         3.4413e-02, -3.2688e-02,  4.0914e-02, -6.5

In [19]:
torch.save(self_generated_dict, 'reinitialize_weights_layer0_layer1.bin')

In [20]:
# new_state_dict = torch.load('reinitialize_weights_layer0_layer1.bin', map_location="cpu")

In [21]:
# for k in new_state_dict.keys():
#     print(k)
#     print(new_state_dict[k].shape)

bert.embeddings.word_embeddings.weight
torch.Size([30522, 768])
bert.embeddings.position_embeddings.weight
torch.Size([512, 768])
bert.embeddings.token_type_embeddings.weight
torch.Size([2, 768])
bert.embeddings.LayerNorm.gamma
torch.Size([768])
bert.embeddings.LayerNorm.beta
torch.Size([768])
bert.encoder.layer.0.attention.self.query.weight
torch.Size([768, 768])
bert.encoder.layer.0.attention.self.query.bias
torch.Size([768])
bert.encoder.layer.0.attention.self.key.weight
torch.Size([768, 768])
bert.encoder.layer.0.attention.self.key.bias
torch.Size([768])
bert.encoder.layer.0.attention.self.value.weight
torch.Size([768, 768])
bert.encoder.layer.0.attention.self.value.bias
torch.Size([768])
bert.encoder.layer.0.attention.output.dense.weight
torch.Size([768, 768])
bert.encoder.layer.0.attention.output.dense.bias
torch.Size([768])
bert.encoder.layer.0.attention.output.LayerNorm.gamma
torch.Size([768])
bert.encoder.layer.0.attention.output.LayerNorm.beta
torch.Size([768])
bert.encoder.l

In [66]:
# self_generated_dict['bert.encoder.layer.0.attention.self.query.weight'][20]

In [22]:

# self_generated_dict['bert.encoder.layer.0.attention.self.query.weight'].shape

torch.Size([768, 768])

In [48]:
# state_dict['bert.encoder.layer.0.attention.self.query.weight'].shape

torch.Size([768, 768])

In [23]:
# new_state_dict['bert.encoder.layer.0.attention.self.query.weight'].shape

torch.Size([768, 768])